// <auto-generated />
using System;
using Estigo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estigo.Migrations
{
    [DbContext(typeof(EstigoDbContext))]
    [Migration("20250408202144_update_studentexamresult")]
    partial class update_studentexamresult
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Estigo.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Estigo.Models.BankOfQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("OptionA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("BankOfQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "A",
                            ExamId = 11,
                            OptionA = "Paris",
                            OptionB = "London",
                            OptionC = "Rome",
                            OptionD = "Berlin",
                            QuestionText = "What is the capital of France?"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "B",
                            ExamId = 11,
                            OptionA = "Earth",
                            OptionB = "Mars",
                            OptionC = "Jupiter",
                            OptionD = "Saturn",
                            QuestionText = "Which planet is known as the Red Planet?"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = "C",
                            ExamId = 11,
                            OptionA = "10",
                            OptionB = "11",
                            OptionC = "12",
                            OptionD = "13",
                            QuestionText = "What is 5 + 7?"
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = "C",
                            ExamId = 11,
                            OptionA = "Java",
                            OptionB = "Swift",
                            OptionC = "Kotlin",
                            OptionD = "C#",
                            QuestionText = "Which language is primarily used for Android development?"
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswer = "A",
                            ExamId = 11,
                            OptionA = "H2O",
                            OptionB = "O2",
                            OptionC = "CO2",
                            OptionD = "NaCl",
                            QuestionText = "What is the chemical symbol for water?"
                        },
                        new
                        {
                            Id = 6,
                            CorrectAnswer = "B",
                            ExamId = 12,
                            OptionA = "8",
                            OptionB = "9",
                            OptionC = "10",
                            OptionD = "7",
                            QuestionText = "What is the square root of 81?"
                        },
                        new
                        {
                            Id = 7,
                            CorrectAnswer = "B",
                            ExamId = 12,
                            OptionA = "Vincent van Gogh",
                            OptionB = "Leonardo da Vinci",
                            OptionC = "Pablo Picasso",
                            OptionD = "Michelangelo",
                            QuestionText = "Who painted the Mona Lisa?"
                        },
                        new
                        {
                            Id = 8,
                            CorrectAnswer = "D",
                            ExamId = 12,
                            OptionA = "Brain",
                            OptionB = "Lungs",
                            OptionC = "Liver",
                            OptionD = "Heart",
                            QuestionText = "Which organ pumps blood through the body?"
                        },
                        new
                        {
                            Id = 9,
                            CorrectAnswer = "C",
                            ExamId = 12,
                            OptionA = "Earth",
                            OptionB = "Mars",
                            OptionC = "Jupiter",
                            OptionD = "Saturn",
                            QuestionText = "What is the largest planet in our solar system?"
                        },
                        new
                        {
                            Id = 10,
                            CorrectAnswer = "B",
                            ExamId = 12,
                            OptionA = "Oxygen",
                            OptionB = "Hydrogen",
                            OptionC = "Helium",
                            OptionD = "Carbon",
                            QuestionText = "Which element has the atomic number 1?"
                        });
                });

            modelBuilder.Entity("Estigo.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 5,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("Estigo.Models.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChapterId"));

                    b.Property<string>("ChapterTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ChapterId");

                    b.ToTable("Chapter");
                });

            modelBuilder.Entity("Estigo.Models.Course", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("courseId"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("TeacherId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("courseId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            courseId = 1,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Algebra | Unit 1",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to algebraic concepts",
                            Price = 199,
                            TeacherId = "t1"
                        },
                        new
                        {
                            courseId = 2,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Calculus | Unit 2",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fundamentals of differential calculus",
                            Price = 199,
                            TeacherId = "t2"
                        },
                        new
                        {
                            courseId = 3,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Geometry | Unit 3",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basics of geometric shapes and theorems",
                            Price = 189,
                            TeacherId = "t1"
                        },
                        new
                        {
                            courseId = 4,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Trigonometry | Unit 4",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Understanding angles and trigonometric functions",
                            Price = 189,
                            TeacherId = "t2"
                        },
                        new
                        {
                            courseId = 5,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Statistics | Unit 5",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to data analysis and probability",
                            Price = 179,
                            TeacherId = "t1"
                        },
                        new
                        {
                            courseId = 6,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Probability | Unit 6",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Exploring probability theories and applications",
                            Price = 179,
                            TeacherId = "t2"
                        },
                        new
                        {
                            courseId = 7,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Discrete Math | Unit 7",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fundamentals of logic, set theory, and combinatorics",
                            Price = 189,
                            TeacherId = "t1"
                        },
                        new
                        {
                            courseId = 8,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Mechanics | Unit 1",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to Newtonian mechanics",
                            Price = 149,
                            TeacherId = "t3"
                        },
                        new
                        {
                            courseId = 9,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Electricity | Unit 2",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basics of electric circuits and fields",
                            Price = 149,
                            TeacherId = "t4"
                        },
                        new
                        {
                            courseId = 10,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Magnetism | Unit 3",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Principles of magnetic forces and fields",
                            Price = 159,
                            TeacherId = "t5"
                        },
                        new
                        {
                            courseId = 11,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Optics | Unit 4",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Study of light behavior and properties",
                            Price = 159,
                            TeacherId = "t3"
                        },
                        new
                        {
                            courseId = 12,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Thermodynamics | Unit 5",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fundamentals of heat and energy",
                            Price = 169,
                            TeacherId = "t4"
                        },
                        new
                        {
                            courseId = 13,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Quantum Physics | Unit 6",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to quantum theory",
                            Price = 169,
                            TeacherId = "t5"
                        },
                        new
                        {
                            courseId = 14,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Relativity | Unit 7",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Concepts of special and general relativity",
                            Price = 169,
                            TeacherId = "t3"
                        },
                        new
                        {
                            courseId = 15,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Cell Biology | Unit 1",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Study of cell structure and function",
                            Price = 179,
                            TeacherId = "t6"
                        },
                        new
                        {
                            courseId = 16,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Genetics | Unit 2",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to heredity and DNA",
                            Price = 179,
                            TeacherId = "t7"
                        },
                        new
                        {
                            courseId = 17,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Movement | Unit 3",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Principles of Movement",
                            Price = 189,
                            TeacherId = "t6"
                        },
                        new
                        {
                            courseId = 18,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Ecology | Unit 4",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basics of ecosystems and environment",
                            Price = 189,
                            TeacherId = "t7"
                        },
                        new
                        {
                            courseId = 19,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Botany | Unit 5",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Study of plant biology and physiology",
                            Price = 179,
                            TeacherId = "t6"
                        },
                        new
                        {
                            courseId = 20,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Zoology | Unit 6",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to animal biology",
                            Price = 179,
                            TeacherId = "t7"
                        },
                        new
                        {
                            courseId = 21,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Microbiology | Unit 7",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basics of microorganisms and their roles",
                            Price = 189,
                            TeacherId = "t6"
                        },
                        new
                        {
                            courseId = 22,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Organic Chemistry | Unit 1",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to organic compounds",
                            Price = 159,
                            TeacherId = "t8"
                        },
                        new
                        {
                            courseId = 23,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Inorganic Chemistry | Unit 2",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fundamentals of inorganic substances",
                            Price = 159,
                            TeacherId = "t9"
                        },
                        new
                        {
                            courseId = 24,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Physical Chemistry | Unit 3",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Study of chemical thermodynamics and kinetics",
                            Price = 169,
                            TeacherId = "t10"
                        },
                        new
                        {
                            courseId = 25,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Analytical Chemistry | Unit 4",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Techniques for chemical analysis",
                            Price = 169,
                            TeacherId = "t11"
                        },
                        new
                        {
                            courseId = 26,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Biochemistry | Unit 5",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chemical processes within living organisms",
                            Price = 179,
                            TeacherId = "t8"
                        },
                        new
                        {
                            courseId = 27,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Environmental Chemistry | Unit 6",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chemistry in environmental processes",
                            Price = 179,
                            TeacherId = "t9"
                        },
                        new
                        {
                            courseId = 28,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Theoretical Chemistry | Unit 7",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conceptual frameworks of chemical behavior",
                            Price = 169,
                            TeacherId = "t10"
                        },
                        new
                        {
                            courseId = 29,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Literature | Unit 1",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Exploring classic and modern literature",
                            Price = 129,
                            TeacherId = "t12"
                        },
                        new
                        {
                            courseId = 30,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Creative Writing | Unit 2",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Develop storytelling and narrative skills",
                            Price = 129,
                            TeacherId = "t13"
                        },
                        new
                        {
                            courseId = 31,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Grammar & Composition | Unit 3",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mastering the rules of English grammar",
                            Price = 119,
                            TeacherId = "t12"
                        },
                        new
                        {
                            courseId = 32,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Poetry Analysis | Unit 4",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Study and analysis of poetry",
                            Price = 119,
                            TeacherId = "t13"
                        },
                        new
                        {
                            courseId = 33,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Drama & Theater | Unit 5",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to dramatic literature and performance",
                            Price = 129,
                            TeacherId = "t12"
                        },
                        new
                        {
                            courseId = 34,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Fiction Writing | Unit 6",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Techniques for writing compelling fiction",
                            Price = 129,
                            TeacherId = "t13"
                        },
                        new
                        {
                            courseId = 35,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Non-fiction Writing | Unit 7",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crafting engaging non-fiction narratives",
                            Price = 119,
                            TeacherId = "t12"
                        });
                });

            modelBuilder.Entity("Estigo.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ExamDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<int>("lessonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("courseId");

                    b.HasIndex("lessonId")
                        .IsUnique();

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 4, 8, 20, 21, 41, 355, DateTimeKind.Utc).AddTicks(3505),
                            ExamDescription = "Test your knowledge of C# basics.",
                            ExamTitle = "Exam: Introduction to C#",
                            Grade = "Not Graded",
                            courseId = 1,
                            lessonId = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 4, 8, 20, 21, 41, 355, DateTimeKind.Utc).AddTicks(4086),
                            ExamDescription = "Variables and types quiz.",
                            ExamTitle = "Exam: Variables and Data Types",
                            Grade = "Not Graded",
                            courseId = 1,
                            lessonId = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 4, 8, 20, 21, 41, 355, DateTimeKind.Utc).AddTicks(4089),
                            ExamDescription = "Control flow evaluation.",
                            ExamTitle = "Exam: Control Structures",
                            Grade = "Not Graded",
                            courseId = 1,
                            lessonId = 13
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 4, 8, 20, 21, 41, 355, DateTimeKind.Utc).AddTicks(4091),
                            ExamDescription = "Function usage test.",
                            ExamTitle = "Exam: Functions",
                            Grade = "Not Graded",
                            courseId = 1,
                            lessonId = 14
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 4, 8, 20, 21, 41, 355, DateTimeKind.Utc).AddTicks(4126),
                            ExamDescription = "OOP concepts in C#.",
                            ExamTitle = "Exam: Classes and Objects",
                            Grade = "Not Graded",
                            courseId = 1,
                            lessonId = 15
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 4, 8, 20, 21, 41, 355, DateTimeKind.Utc).AddTicks(4128),
                            ExamDescription = "Test your knowledge of C# basics.",
                            ExamTitle = "Exam: Introduction to C#",
                            Grade = "Not Graded",
                            courseId = 2,
                            lessonId = 16
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 4, 8, 20, 21, 41, 355, DateTimeKind.Utc).AddTicks(4130),
                            ExamDescription = "Variables and types quiz.",
                            ExamTitle = "Exam: Variables and Data Types",
                            Grade = "Not Graded",
                            courseId = 2,
                            lessonId = 17
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 4, 8, 20, 21, 41, 355, DateTimeKind.Utc).AddTicks(4132),
                            ExamDescription = "Control flow evaluation.",
                            ExamTitle = "Exam: Control Structures",
                            Grade = "Not Graded",
                            courseId = 2,
                            lessonId = 18
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 4, 8, 20, 21, 41, 355, DateTimeKind.Utc).AddTicks(4134),
                            ExamDescription = "Function usage test.",
                            ExamTitle = "Exam: Functions",
                            Grade = "Not Graded",
                            courseId = 2,
                            lessonId = 19
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 4, 8, 20, 21, 41, 355, DateTimeKind.Utc).AddTicks(4136),
                            ExamDescription = "OOP concepts in C#.",
                            ExamTitle = "Exam: Classes and Objects",
                            Grade = "Not Graded",
                            courseId = 2,
                            lessonId = 20
                        });
                });

            modelBuilder.Entity("Estigo.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PaymentId");

                    b.HasIndex("courseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Estigo.Models.StudentExamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExamDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentExamResults");
                });

            modelBuilder.Entity("Estigo.Models.lesson", b =>
                {
                    b.Property<int>("lessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lessonId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<int?>("examId")
                        .HasColumnType("int");

                    b.Property<string>("lessonContent")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("lessonDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("lessonTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("lessonVideo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("lessonId");

                    b.HasIndex("courseId");

                    b.ToTable("lessons");

                    b.HasData(
                        new
                        {
                            lessonId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 1,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "This lesson covers the basics of C# programming.",
                            lessonTitle = "Introduction to C#",
                            lessonVideo = "http://localhost:5070/vv.mp4"
                        },
                        new
                        {
                            lessonId = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 1,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn about variables and data types in C#.",
                            lessonTitle = "C# Variables and Data Types",
                            lessonVideo = "http://localhost:5070/cat.mp4"
                        },
                        new
                        {
                            lessonId = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 1,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn about control structures in C#.",
                            lessonTitle = "C# Control Structures",
                            lessonVideo = "vv.mp4"
                        },
                        new
                        {
                            lessonId = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 1,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn how to define and call functions in C#.",
                            lessonTitle = "C# Functions",
                            lessonVideo = "vv.mp4"
                        },
                        new
                        {
                            lessonId = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 1,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn about classes and objects in C#.",
                            lessonTitle = "C# Classes and Objects",
                            lessonVideo = "http://path/to/lesson5_video.mp4"
                        },
                        new
                        {
                            lessonId = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 2,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "This lesson covers the basics of C# programming.",
                            lessonTitle = "Introduction to C#",
                            lessonVideo = "http://path/to/lesson1_video.mp4"
                        },
                        new
                        {
                            lessonId = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 2,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn about variables and data types in C#.",
                            lessonTitle = "C# Variables and Data Types",
                            lessonVideo = "http://path/to/lesson2_video.mp4"
                        },
                        new
                        {
                            lessonId = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 2,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn about control structures in C#.",
                            lessonTitle = "C# Control Structures",
                            lessonVideo = "http://path/to/lesson3_video.mp4"
                        },
                        new
                        {
                            lessonId = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 2,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn how to define and call functions in C#.",
                            lessonTitle = "C# Functions",
                            lessonVideo = "http://path/to/lesson4_video.mp4"
                        },
                        new
                        {
                            lessonId = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 2,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn about classes and objects in C#.",
                            lessonTitle = "C# Classes and Objects",
                            lessonVideo = "http://path/to/lesson5_video.mp4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyCourse", b =>
                {
                    b.Property<int>("MycourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MycourseId"));

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MycourseId");

                    b.HasIndex("courseId");

                    b.HasIndex("StudentId");

                    b.ToTable("MyCourses", (string)null);
                });

            modelBuilder.Entity("Estigo.Models.Admin", b =>
                {
                    b.HasBaseType("Estigo.Models.ApplicationUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Estigo.Models.Parent", b =>
                {
                    b.HasBaseType("Estigo.Models.ApplicationUser");

                    b.HasDiscriminator().HasValue("Parent");
                });

            modelBuilder.Entity("Estigo.Models.Student", b =>
                {
                    b.HasBaseType("Estigo.Models.ApplicationUser");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("ParentPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Track")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("Estigo.Models.Teacher", b =>
                {
                    b.HasBaseType("Estigo.Models.ApplicationUser");

                    b.Property<int?>("courseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("image")
                        .HasColumnType("varbinary(max)");

                    b.HasDiscriminator().HasValue("Teacher");

                    b.HasData(
                        new
                        {
                            Id = "t1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aac95750-be35-4257-91ba-9d898864a282",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "math1@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "Mahmoud",
                            NormalizedEmail = "MATH1@ESTIGO.COM",
                            NormalizedUserName = "MATH1@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "52ed97da-18d9-4d2a-b679-bc27d2cc9cb9",
                            TwoFactorEnabled = false,
                            UserName = "math1@estigo.com",
                            Notes = "Expert in Algebra",
                            Subject = "Mathematics"
                        },
                        new
                        {
                            Id = "t2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9de37b21-2088-468a-b72c-b21e1b4abd45",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "math2@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "Mousa",
                            NormalizedEmail = "MATH2@ESTIGO.COM",
                            NormalizedUserName = "MATH2@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "c1f056ef-ca36-4ddb-b68c-7c7e006b6fcc",
                            TwoFactorEnabled = false,
                            UserName = "math2@estigo.com",
                            Notes = "Specialist in Calculus",
                            Subject = "Mathematics"
                        },
                        new
                        {
                            Id = "t3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c29dd9b0-d0c0-4a41-b1c0-e4469993dec9",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "phys1@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            Name = "Amira",
                            NormalizedEmail = "PHYS1@ESTIGO.COM",
                            NormalizedUserName = "PHYS1@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "395c2c56-0156-4c6a-a38e-1805611e6973",
                            TwoFactorEnabled = false,
                            UserName = "phys1@estigo.com",
                            Notes = "Specialist in Mechanics",
                            Subject = "Physics"
                        },
                        new
                        {
                            Id = "t4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "41c612c4-1b5d-4972-b54e-250eeb92a183",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "phys2@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            Name = "Noura",
                            NormalizedEmail = "PHYS2@ESTIGO.COM",
                            NormalizedUserName = "PHYS2@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "4c4d25e3-40fb-4f97-939a-c117cae40b3d",
                            TwoFactorEnabled = false,
                            UserName = "phys2@estigo.com",
                            Notes = "Expert in Electromagnetism",
                            Subject = "Physics"
                        },
                        new
                        {
                            Id = "t5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9fbb9e55-e5e0-4406-b2e3-17a079e15c10",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "phys3@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "Mustafa",
                            NormalizedEmail = "PHYS3@ESTIGO.COM",
                            NormalizedUserName = "PHYS3@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "031b79d0-d3ff-45d4-828f-45d5953ad733",
                            TwoFactorEnabled = false,
                            UserName = "phys3@estigo.com",
                            Notes = "Enthusiast in Quantum Physics",
                            Subject = "Physics"
                        },
                        new
                        {
                            Id = "t6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10c76324-e0b2-42e2-9a9f-8366be46ab53",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bio1@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "Ahmed",
                            NormalizedEmail = "BIO1@ESTIGO.COM",
                            NormalizedUserName = "BIO1@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "630823cb-6c68-4974-bf90-41d7b7bfad0d",
                            TwoFactorEnabled = false,
                            UserName = "bio1@estigo.com",
                            Notes = "Expert in Cell Biology",
                            Subject = "Biology"
                        },
                        new
                        {
                            Id = "t7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3ea7f272-8e37-4301-819f-28a3329cacd5",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bio2@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "Karim",
                            NormalizedEmail = "BIO2@ESTIGO.COM",
                            NormalizedUserName = "BIO2@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "72ae449f-977f-4543-83b8-487f37fafb84",
                            TwoFactorEnabled = false,
                            UserName = "bio2@estigo.com",
                            Notes = "Specialist in Genetics",
                            Subject = "Biology"
                        },
                        new
                        {
                            Id = "t8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "24a9adb2-a2df-4db4-bdd7-b39bb3576adf",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chem1@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "Mohamed",
                            NormalizedEmail = "CHEM1@ESTIGO.COM",
                            NormalizedUserName = "CHEM1@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "aa50949b-1017-4b70-8cd7-bc490e048dd6",
                            TwoFactorEnabled = false,
                            UserName = "chem1@estigo.com",
                            Notes = "Passionate about Organic Chemistry",
                            Subject = "Chemistry"
                        },
                        new
                        {
                            Id = "t9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8b714f06-b7cc-4cf1-8641-0f23644782d7",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chem2@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            Name = "Noura",
                            NormalizedEmail = "CHEM2@ESTIGO.COM",
                            NormalizedUserName = "CHEM2@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "decc4b45-1e3e-4f28-89af-0e2620fcaf2d",
                            TwoFactorEnabled = false,
                            UserName = "chem2@estigo.com",
                            Notes = "Expert in Inorganic Chemistry",
                            Subject = "Chemistry"
                        },
                        new
                        {
                            Id = "t10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10db8ff5-eb23-4660-979b-30c7e1c41df7",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chem3@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "Fahad",
                            NormalizedEmail = "CHEM3@ESTIGO.COM",
                            NormalizedUserName = "CHEM3@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "65d1e6c9-7177-47ba-805d-b8bb8ea4b677",
                            TwoFactorEnabled = false,
                            UserName = "chem3@estigo.com",
                            Notes = "Skilled in Analytical Chemistry",
                            Subject = "Chemistry"
                        },
                        new
                        {
                            Id = "t11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "32bb1d91-1073-4b79-a584-eda0019f3bfe",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chem4@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            Name = "Sara",
                            NormalizedEmail = "CHEM4@ESTIGO.COM",
                            NormalizedUserName = "CHEM4@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "fd3d9c7a-1de1-4f0b-b6e1-1f65c2ca0fda",
                            TwoFactorEnabled = false,
                            UserName = "chem4@estigo.com",
                            Notes = "Focused on Physical Chemistry",
                            Subject = "Chemistry"
                        },
                        new
                        {
                            Id = "t12",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e98c5356-064c-40f9-b729-18e62c019e51",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eng1@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            Name = "Sarah",
                            NormalizedEmail = "ENG1@ESTIGO.COM",
                            NormalizedUserName = "ENG1@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "bfa14214-9895-4f5d-8566-fcc5419d865b",
                            TwoFactorEnabled = false,
                            UserName = "eng1@estigo.com",
                            Notes = "Literature Specialist",
                            Subject = "English"
                        },
                        new
                        {
                            Id = "t13",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8d0e47ac-6189-478b-b6fc-dd08924ce545",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eng2@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "John",
                            NormalizedEmail = "ENG2@ESTIGO.COM",
                            NormalizedUserName = "ENG2@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "5f6beb96-a7fd-473c-9099-2476441eab8f",
                            TwoFactorEnabled = false,
                            UserName = "eng2@estigo.com",
                            Notes = "Expert in Creative Writing",
                            Subject = "English"
                        });
                });

            modelBuilder.Entity("Estigo.Models.BankOfQuestion", b =>
                {
                    b.HasOne("Estigo.Models.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Estigo.Models.Course", b =>
                {
                    b.HasOne("Estigo.Models.Category", null)
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estigo.Models.Teacher", "Teacher")
                        .WithMany("CoursesTaught")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Estigo.Models.Exam", b =>
                {
                    b.HasOne("Estigo.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estigo.Models.lesson", "Lesson")
                        .WithOne("Exam")
                        .HasForeignKey("Estigo.Models.Exam", "lessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Estigo.Models.Payment", b =>
                {
                    b.HasOne("Estigo.Models.Course", "Course")
                        .WithMany("Payments")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estigo.Models.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Estigo.Models.StudentExamResult", b =>
                {
                    b.HasOne("Estigo.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estigo.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Estigo.Models.lesson", b =>
                {
                    b.HasOne("Estigo.Models.Course", "Course")
                        .WithMany("lessons")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Estigo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Estigo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estigo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Estigo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCourse", b =>
                {
                    b.HasOne("Estigo.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estigo.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Estigo.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Estigo.Models.Course", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("lessons");
                });

            modelBuilder.Entity("Estigo.Models.Exam", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Estigo.Models.lesson", b =>
                {
                    b.Navigation("Exam")
                        .IsRequired();
                });

            modelBuilder.Entity("Estigo.Models.Student", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Estigo.Models.Teacher", b =>
                {
                    b.Navigation("CoursesTaught");
                });
#pragma warning restore 612, 618
        }
    }
}
