// <auto-generated />
using System;
using Estigo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estigo.Migrations
{
    [DbContext(typeof(EstigoDbContext))]
    partial class EstigoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankOfQuestionExam", b =>
                {
                    b.Property<int>("ExamsId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("int");

                    b.HasKey("ExamsId", "QuestionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("BankOfQuestionExam");
                });

            modelBuilder.Entity("Estigo.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("UserType").HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Estigo.Models.BankOfQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankOfQuestions");
                });

            modelBuilder.Entity("Estigo.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 5,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("Estigo.Models.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChapterId"));

                    b.Property<string>("ChapterTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ChapterId");

                    b.ToTable("Chapter");
                });

            modelBuilder.Entity("Estigo.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("TeacherId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("CourseId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Algebra | Unit 1",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to algebraic concepts",
                            Price = 199,
                            TeacherId = "t1"
                        },
                        new
                        {
                            CourseId = 2,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Calculus | Unit 2",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fundamentals of differential calculus",
                            Price = 199,
                            TeacherId = "t2"
                        },
                        new
                        {
                            CourseId = 3,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Geometry | Unit 3",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basics of geometric shapes and theorems",
                            Price = 189,
                            TeacherId = "t1"
                        },
                        new
                        {
                            CourseId = 4,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Trigonometry | Unit 4",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Understanding angles and trigonometric functions",
                            Price = 189,
                            TeacherId = "t2"
                        },
                        new
                        {
                            CourseId = 5,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Statistics | Unit 5",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to data analysis and probability",
                            Price = 179,
                            TeacherId = "t1"
                        },
                        new
                        {
                            CourseId = 6,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Probability | Unit 6",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Exploring probability theories and applications",
                            Price = 179,
                            TeacherId = "t2"
                        },
                        new
                        {
                            CourseId = 7,
                            Available = true,
                            CategoryId = 1,
                            CourseTitle = "Discrete Math | Unit 7",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fundamentals of logic, set theory, and combinatorics",
                            Price = 189,
                            TeacherId = "t1"
                        },
                        new
                        {
                            CourseId = 8,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Mechanics | Unit 1",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to Newtonian mechanics",
                            Price = 149,
                            TeacherId = "t3"
                        },
                        new
                        {
                            CourseId = 9,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Electricity | Unit 2",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basics of electric circuits and fields",
                            Price = 149,
                            TeacherId = "t4"
                        },
                        new
                        {
                            CourseId = 10,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Magnetism | Unit 3",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Principles of magnetic forces and fields",
                            Price = 159,
                            TeacherId = "t5"
                        },
                        new
                        {
                            CourseId = 11,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Optics | Unit 4",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Study of light behavior and properties",
                            Price = 159,
                            TeacherId = "t3"
                        },
                        new
                        {
                            CourseId = 12,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Thermodynamics | Unit 5",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fundamentals of heat and energy",
                            Price = 169,
                            TeacherId = "t4"
                        },
                        new
                        {
                            CourseId = 13,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Quantum Physics | Unit 6",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to quantum theory",
                            Price = 169,
                            TeacherId = "t5"
                        },
                        new
                        {
                            CourseId = 14,
                            Available = true,
                            CategoryId = 2,
                            CourseTitle = "Relativity | Unit 7",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Concepts of special and general relativity",
                            Price = 169,
                            TeacherId = "t3"
                        },
                        new
                        {
                            CourseId = 15,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Cell Biology | Unit 1",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Study of cell structure and function",
                            Price = 179,
                            TeacherId = "t6"
                        },
                        new
                        {
                            CourseId = 16,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Genetics | Unit 2",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to heredity and DNA",
                            Price = 179,
                            TeacherId = "t7"
                        },
                        new
                        {
                            CourseId = 17,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Movement | Unit 3",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Principles of Movement",
                            Price = 189,
                            TeacherId = "t6"
                        },
                        new
                        {
                            CourseId = 18,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Ecology | Unit 4",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basics of ecosystems and environment",
                            Price = 189,
                            TeacherId = "t7"
                        },
                        new
                        {
                            CourseId = 19,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Botany | Unit 5",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Study of plant biology and physiology",
                            Price = 179,
                            TeacherId = "t6"
                        },
                        new
                        {
                            CourseId = 20,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Zoology | Unit 6",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to animal biology",
                            Price = 179,
                            TeacherId = "t7"
                        },
                        new
                        {
                            CourseId = 21,
                            Available = true,
                            CategoryId = 3,
                            CourseTitle = "Microbiology | Unit 7",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basics of microorganisms and their roles",
                            Price = 189,
                            TeacherId = "t6"
                        },
                        new
                        {
                            CourseId = 22,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Organic Chemistry | Unit 1",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to organic compounds",
                            Price = 159,
                            TeacherId = "t8"
                        },
                        new
                        {
                            CourseId = 23,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Inorganic Chemistry | Unit 2",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Fundamentals of inorganic substances",
                            Price = 159,
                            TeacherId = "t9"
                        },
                        new
                        {
                            CourseId = 24,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Physical Chemistry | Unit 3",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Study of chemical thermodynamics and kinetics",
                            Price = 169,
                            TeacherId = "t10"
                        },
                        new
                        {
                            CourseId = 25,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Analytical Chemistry | Unit 4",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Techniques for chemical analysis",
                            Price = 169,
                            TeacherId = "t11"
                        },
                        new
                        {
                            CourseId = 26,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Biochemistry | Unit 5",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chemical processes within living organisms",
                            Price = 179,
                            TeacherId = "t8"
                        },
                        new
                        {
                            CourseId = 27,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Environmental Chemistry | Unit 6",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chemistry in environmental processes",
                            Price = 179,
                            TeacherId = "t9"
                        },
                        new
                        {
                            CourseId = 28,
                            Available = true,
                            CategoryId = 4,
                            CourseTitle = "Theoretical Chemistry | Unit 7",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conceptual frameworks of chemical behavior",
                            Price = 169,
                            TeacherId = "t10"
                        },
                        new
                        {
                            CourseId = 29,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Literature | Unit 1",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Exploring classic and modern literature",
                            Price = 129,
                            TeacherId = "t12"
                        },
                        new
                        {
                            CourseId = 30,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Creative Writing | Unit 2",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Develop storytelling and narrative skills",
                            Price = 129,
                            TeacherId = "t13"
                        },
                        new
                        {
                            CourseId = 31,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Grammar & Composition | Unit 3",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mastering the rules of English grammar",
                            Price = 119,
                            TeacherId = "t12"
                        },
                        new
                        {
                            CourseId = 32,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Poetry Analysis | Unit 4",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Study and analysis of poetry",
                            Price = 119,
                            TeacherId = "t13"
                        },
                        new
                        {
                            CourseId = 33,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Drama & Theater | Unit 5",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Introduction to dramatic literature and performance",
                            Price = 129,
                            TeacherId = "t12"
                        },
                        new
                        {
                            CourseId = 34,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Fiction Writing | Unit 6",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Techniques for writing compelling fiction",
                            Price = 129,
                            TeacherId = "t13"
                        },
                        new
                        {
                            CourseId = 35,
                            Available = true,
                            CategoryId = 5,
                            CourseTitle = "Non-fiction Writing | Unit 7",
                            CreatedAt = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Crafting engaging non-fiction narratives",
                            Price = 119,
                            TeacherId = "t12"
                        });
                });

            modelBuilder.Entity("Estigo.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ExamDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExamTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<int>("lessonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("courseId");

                    b.HasIndex("lessonId")
                        .IsUnique();

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 4, 5, 21, 22, 58, 969, DateTimeKind.Utc).AddTicks(4036),
                            ExamDescription = "Test your knowledge of C# basics.",
                            ExamTitle = "Exam: Introduction to C#",
                            Grade = "Not Graded",
                            courseId = 1,
                            lessonId = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 4, 5, 21, 22, 58, 969, DateTimeKind.Utc).AddTicks(4596),
                            ExamDescription = "Variables and types quiz.",
                            ExamTitle = "Exam: Variables and Data Types",
                            Grade = "Not Graded",
                            courseId = 1,
                            lessonId = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 4, 5, 21, 22, 58, 969, DateTimeKind.Utc).AddTicks(4598),
                            ExamDescription = "Control flow evaluation.",
                            ExamTitle = "Exam: Control Structures",
                            Grade = "Not Graded",
                            courseId = 1,
                            lessonId = 13
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 4, 5, 21, 22, 58, 969, DateTimeKind.Utc).AddTicks(4600),
                            ExamDescription = "Function usage test.",
                            ExamTitle = "Exam: Functions",
                            Grade = "Not Graded",
                            courseId = 1,
                            lessonId = 14
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 4, 5, 21, 22, 58, 969, DateTimeKind.Utc).AddTicks(4602),
                            ExamDescription = "OOP concepts in C#.",
                            ExamTitle = "Exam: Classes and Objects",
                            Grade = "Not Graded",
                            courseId = 1,
                            lessonId = 15
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 4, 5, 21, 22, 58, 969, DateTimeKind.Utc).AddTicks(4604),
                            ExamDescription = "Test your knowledge of C# basics.",
                            ExamTitle = "Exam: Introduction to C#",
                            Grade = "Not Graded",
                            courseId = 2,
                            lessonId = 16
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 4, 5, 21, 22, 58, 969, DateTimeKind.Utc).AddTicks(4606),
                            ExamDescription = "Variables and types quiz.",
                            ExamTitle = "Exam: Variables and Data Types",
                            Grade = "Not Graded",
                            courseId = 2,
                            lessonId = 17
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 4, 5, 21, 22, 58, 969, DateTimeKind.Utc).AddTicks(4608),
                            ExamDescription = "Control flow evaluation.",
                            ExamTitle = "Exam: Control Structures",
                            Grade = "Not Graded",
                            courseId = 2,
                            lessonId = 18
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 4, 5, 21, 22, 58, 969, DateTimeKind.Utc).AddTicks(4610),
                            ExamDescription = "Function usage test.",
                            ExamTitle = "Exam: Functions",
                            Grade = "Not Graded",
                            courseId = 2,
                            lessonId = 19
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 4, 5, 21, 22, 58, 969, DateTimeKind.Utc).AddTicks(4612),
                            ExamDescription = "OOP concepts in C#.",
                            ExamTitle = "Exam: Classes and Objects",
                            Grade = "Not Graded",
                            courseId = 2,
                            lessonId = 20
                        });
                });

            modelBuilder.Entity("Estigo.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PaymentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Estigo.Models.StudentExamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExamDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentExamResults");
                });

            modelBuilder.Entity("Estigo.Models.lesson", b =>
                {
                    b.Property<int>("lessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lessonId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("courseId")
                        .HasColumnType("int");

                    b.Property<int?>("examId")
                        .HasColumnType("int");

                    b.Property<string>("lessonContent")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("lessonDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("lessonTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("lessonVideo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("lessonId");

                    b.HasIndex("courseId");

                    b.ToTable("lessons");

                    b.HasData(
                        new
                        {
                            lessonId = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 1,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "This lesson covers the basics of C# programming.",
                            lessonTitle = "Introduction to C#",
                            lessonVideo = "http://localhost:5070/vv.mp4"
                        },
                        new
                        {
                            lessonId = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 1,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn about variables and data types in C#.",
                            lessonTitle = "C# Variables and Data Types",
                            lessonVideo = "http://localhost:5070/cat.mp4"
                        },
                        new
                        {
                            lessonId = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 1,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn about control structures in C#.",
                            lessonTitle = "C# Control Structures",
                            lessonVideo = "vv.mp4"
                        },
                        new
                        {
                            lessonId = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 1,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn how to define and call functions in C#.",
                            lessonTitle = "C# Functions",
                            lessonVideo = "vv.mp4"
                        },
                        new
                        {
                            lessonId = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 1,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn about classes and objects in C#.",
                            lessonTitle = "C# Classes and Objects",
                            lessonVideo = "http://path/to/lesson5_video.mp4"
                        },
                        new
                        {
                            lessonId = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 2,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "This lesson covers the basics of C# programming.",
                            lessonTitle = "Introduction to C#",
                            lessonVideo = "http://path/to/lesson1_video.mp4"
                        },
                        new
                        {
                            lessonId = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 2,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn about variables and data types in C#.",
                            lessonTitle = "C# Variables and Data Types",
                            lessonVideo = "http://path/to/lesson2_video.mp4"
                        },
                        new
                        {
                            lessonId = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 2,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn about control structures in C#.",
                            lessonTitle = "C# Control Structures",
                            lessonVideo = "http://path/to/lesson3_video.mp4"
                        },
                        new
                        {
                            lessonId = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 2,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn how to define and call functions in C#.",
                            lessonTitle = "C# Functions",
                            lessonVideo = "http://path/to/lesson4_video.mp4"
                        },
                        new
                        {
                            lessonId = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            courseId = 2,
                            lessonContent = "This is the content of the lesson.",
                            lessonDescription = "Learn about classes and objects in C#.",
                            lessonTitle = "C# Classes and Objects",
                            lessonVideo = "http://path/to/lesson5_video.mp4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyCourse", b =>
                {
                    b.Property<int>("MyCourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MyCourseId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MyCourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("MyCourses", (string)null);
                });

            modelBuilder.Entity("Estigo.Models.Admin", b =>
                {
                    b.HasBaseType("Estigo.Models.ApplicationUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Estigo.Models.Parent", b =>
                {
                    b.HasBaseType("Estigo.Models.ApplicationUser");

                    b.HasDiscriminator().HasValue("Parent");
                });

            modelBuilder.Entity("Estigo.Models.Student", b =>
                {
                    b.HasBaseType("Estigo.Models.ApplicationUser");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("ParentPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Track")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("Estigo.Models.Teacher", b =>
                {
                    b.HasBaseType("Estigo.Models.ApplicationUser");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("image")
                        .HasColumnType("varbinary(max)");

                    b.HasDiscriminator().HasValue("Teacher");

                    b.HasData(
                        new
                        {
                            Id = "t1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "348944c1-9ca0-4f2d-865f-fcc79ec6dc4d",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "math1@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "Mahmoud",
                            NormalizedEmail = "MATH1@ESTIGO.COM",
                            NormalizedUserName = "MATH1@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "8a17331c-7e47-44d1-babd-bef847887574",
                            TwoFactorEnabled = false,
                            UserName = "math1@estigo.com",
                            Notes = "Expert in Algebra",
                            Subject = "Mathematics"
                        },
                        new
                        {
                            Id = "t2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "25b5011d-1cd0-42f1-b941-c61c87473d26",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "math2@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "Mousa",
                            NormalizedEmail = "MATH2@ESTIGO.COM",
                            NormalizedUserName = "MATH2@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "8a0e9f2e-39d4-4ded-bbe0-9fe184fd6390",
                            TwoFactorEnabled = false,
                            UserName = "math2@estigo.com",
                            Notes = "Specialist in Calculus",
                            Subject = "Mathematics"
                        },
                        new
                        {
                            Id = "t3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ad67385c-fa39-412c-b104-72a31495fc15",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "phys1@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            Name = "Amira",
                            NormalizedEmail = "PHYS1@ESTIGO.COM",
                            NormalizedUserName = "PHYS1@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "ff1146c1-8bf4-49bf-a15c-8c3e25bc5ce4",
                            TwoFactorEnabled = false,
                            UserName = "phys1@estigo.com",
                            Notes = "Specialist in Mechanics",
                            Subject = "Physics"
                        },
                        new
                        {
                            Id = "t4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7500a86-3063-4f94-80bb-1942acc3e560",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "phys2@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            Name = "Noura",
                            NormalizedEmail = "PHYS2@ESTIGO.COM",
                            NormalizedUserName = "PHYS2@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "1601f772-915c-4228-ac63-2f52c516f1f1",
                            TwoFactorEnabled = false,
                            UserName = "phys2@estigo.com",
                            Notes = "Expert in Electromagnetism",
                            Subject = "Physics"
                        },
                        new
                        {
                            Id = "t5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "04d6083b-2450-4938-af86-bfe541d944c6",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "phys3@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "Mustafa",
                            NormalizedEmail = "PHYS3@ESTIGO.COM",
                            NormalizedUserName = "PHYS3@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "0e21acb0-579e-4268-94ad-8a6e97727896",
                            TwoFactorEnabled = false,
                            UserName = "phys3@estigo.com",
                            Notes = "Enthusiast in Quantum Physics",
                            Subject = "Physics"
                        },
                        new
                        {
                            Id = "t6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ae1455b8-2161-4568-8947-51133d6b5d3b",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bio1@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "Ahmed",
                            NormalizedEmail = "BIO1@ESTIGO.COM",
                            NormalizedUserName = "BIO1@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "a2f20e57-2e32-4b8b-b55d-dee00bcdac18",
                            TwoFactorEnabled = false,
                            UserName = "bio1@estigo.com",
                            Notes = "Expert in Cell Biology",
                            Subject = "Biology"
                        },
                        new
                        {
                            Id = "t7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e6ec68dc-8682-48ca-ad23-f23fed76bfec",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bio2@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "Karim",
                            NormalizedEmail = "BIO2@ESTIGO.COM",
                            NormalizedUserName = "BIO2@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "3bb01d33-4d8b-42b7-92e4-4e0c9b46ef42",
                            TwoFactorEnabled = false,
                            UserName = "bio2@estigo.com",
                            Notes = "Specialist in Genetics",
                            Subject = "Biology"
                        },
                        new
                        {
                            Id = "t8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dfcff67c-fb83-4610-9359-0bb382fad142",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chem1@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "Mohamed",
                            NormalizedEmail = "CHEM1@ESTIGO.COM",
                            NormalizedUserName = "CHEM1@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "6248a4b9-bd70-46fc-a85e-fa0967c0f689",
                            TwoFactorEnabled = false,
                            UserName = "chem1@estigo.com",
                            Notes = "Passionate about Organic Chemistry",
                            Subject = "Chemistry"
                        },
                        new
                        {
                            Id = "t9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8bcf3bfc-a06d-4770-b634-79ff37bafdd1",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chem2@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            Name = "Noura",
                            NormalizedEmail = "CHEM2@ESTIGO.COM",
                            NormalizedUserName = "CHEM2@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "d386ca40-a373-4558-b3e6-8e58d97b45fb",
                            TwoFactorEnabled = false,
                            UserName = "chem2@estigo.com",
                            Notes = "Expert in Inorganic Chemistry",
                            Subject = "Chemistry"
                        },
                        new
                        {
                            Id = "t10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b16fa281-a224-4f5a-8397-d28667a785f8",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chem3@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "Fahad",
                            NormalizedEmail = "CHEM3@ESTIGO.COM",
                            NormalizedUserName = "CHEM3@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "564116b2-cc98-47a3-af72-3b48c1c921c0",
                            TwoFactorEnabled = false,
                            UserName = "chem3@estigo.com",
                            Notes = "Skilled in Analytical Chemistry",
                            Subject = "Chemistry"
                        },
                        new
                        {
                            Id = "t11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a7b428f9-4bd4-4c57-a8de-39a2f9abd53e",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chem4@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            Name = "Sara",
                            NormalizedEmail = "CHEM4@ESTIGO.COM",
                            NormalizedUserName = "CHEM4@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "0ea70487-1a38-4d4e-842e-470516f09a8b",
                            TwoFactorEnabled = false,
                            UserName = "chem4@estigo.com",
                            Notes = "Focused on Physical Chemistry",
                            Subject = "Chemistry"
                        },
                        new
                        {
                            Id = "t12",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "432b3b35-64f3-4c7c-94ab-a9d515d10159",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eng1@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Female",
                            LockoutEnabled = false,
                            Name = "Sarah",
                            NormalizedEmail = "ENG1@ESTIGO.COM",
                            NormalizedUserName = "ENG1@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "9dcd0e38-711f-45db-af42-1f23b29bad45",
                            TwoFactorEnabled = false,
                            UserName = "eng1@estigo.com",
                            Notes = "Literature Specialist",
                            Subject = "English"
                        },
                        new
                        {
                            Id = "t13",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "62f15097-7b3f-4003-80ac-b3d03a27466d",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "eng2@estigo.com",
                            EmailConfirmed = false,
                            Gender = "Male",
                            LockoutEnabled = false,
                            Name = "John",
                            NormalizedEmail = "ENG2@ESTIGO.COM",
                            NormalizedUserName = "ENG2@ESTIGO.COM",
                            PhoneNumberConfirmed = false,
                            Role = "Teacher",
                            SecurityStamp = "0698632a-4d7e-4261-8600-9d3df1bbf889",
                            TwoFactorEnabled = false,
                            UserName = "eng2@estigo.com",
                            Notes = "Expert in Creative Writing",
                            Subject = "English"
                        });
                });

            modelBuilder.Entity("BankOfQuestionExam", b =>
                {
                    b.HasOne("Estigo.Models.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estigo.Models.BankOfQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Estigo.Models.Course", b =>
                {
                    b.HasOne("Estigo.Models.Category", null)
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estigo.Models.Teacher", "Teacher")
                        .WithMany("CoursesTaught")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Estigo.Models.Exam", b =>
                {
                    b.HasOne("Estigo.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estigo.Models.lesson", "Lesson")
                        .WithOne("Exam")
                        .HasForeignKey("Estigo.Models.Exam", "lessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("Estigo.Models.Payment", b =>
                {
                    b.HasOne("Estigo.Models.Course", "Course")
                        .WithMany("Payments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estigo.Models.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Estigo.Models.StudentExamResult", b =>
                {
                    b.HasOne("Estigo.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estigo.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Estigo.Models.lesson", b =>
                {
                    b.HasOne("Estigo.Models.Course", "Course")
                        .WithMany("lessons")
                        .HasForeignKey("courseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Estigo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Estigo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estigo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Estigo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyCourse", b =>
                {
                    b.HasOne("Estigo.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Estigo.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Estigo.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Estigo.Models.Course", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("lessons");
                });

            modelBuilder.Entity("Estigo.Models.lesson", b =>
                {
                    b.Navigation("Exam")
                        .IsRequired();
                });

            modelBuilder.Entity("Estigo.Models.Student", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Estigo.Models.Teacher", b =>
                {
                    b.Navigation("CoursesTaught");
                });
#pragma warning restore 612, 618
        }
    }
}
